"use client";

import { useState } from "react";
import toast from "react-hot-toast";
import { API_BASE_URL } from "@/util/APIGeneric";

type InputFieldProps = {
  label: string;
  name: string;
  value: string | number;
  onChange: (e: any) => void;
  placeholder?: string;
  type?: string;
};

export default function AddReportPage() {
  const [loading, setLoading] = useState(false);

  const [formData, setFormData] = useState({
    reportId: "",

    reportType: "Assessment Performance Report",

    generatedBy: "",

    assessmentId: "",

    campaignId: "",

    averageScore: "",
    highestScore: "",
    lowestScore: "",

    completionRate: "",

    suspiciousActivities: "",

    exportedFormat: "PDF",

    generatedAt: "",
  });

  // HANDLE CHANGE
  const handleChange = (e: any) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value,
    });
  };

  // SUBMIT
  const handleSubmit = async (e: any) => {
    e.preventDefault();

    setLoading(true);

    try {
      const finalData = {
        ...formData,

        averageScore: Number(formData.averageScore),

        highestScore: Number(formData.highestScore),

        lowestScore: Number(formData.lowestScore),

        completionRate: Number(formData.completionRate),

        suspiciousActivities: Number(formData.suspiciousActivities),
      };

      const response = await fetch(
        `${API_BASE_URL}/report/create`,
        {
          method: "POST",

          headers: {
            "Content-Type": "application/json",
          },

          body: JSON.stringify(finalData),
        }
      );

      const data = await response.json();

      if (response.ok) {
        toast.success("Report Added Successfully");

        // RESET FORM
        setFormData({
          reportId: "",

          reportType: "Assessment Performance Report",

          generatedBy: "",

          assessmentId: "",

          campaignId: "",

          averageScore: "",
          highestScore: "",
          lowestScore: "",

          completionRate: "",

          suspiciousActivities: "",

          exportedFormat: "PDF",

          generatedAt: "",
        });
      } else {
        toast.error(data.message || "Failed To Add Report");
      }
    } catch (error) {
      toast.error("Something went wrong");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-gray-100 p-6">
      <div className="max-w-7xl mx-auto bg-white rounded-[30px] shadow-xl overflow-hidden border border-gray-200">
        {/* HEADER */}
        <div className="bg-linear-to-r from-blue-600 to-indigo-600 px-8 py-6">
          <h1 className="text-3xl font-bold text-white">Add New Report</h1>

          <p className="text-blue-100 mt-2">
            Fill all report details carefully
          </p>
        </div>

        {/* FORM */}
        <form onSubmit={handleSubmit} className="p-8">
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {/* REPORT ID */}
            <InputField
              label="Report ID"
              name="reportId"
              value={formData.reportId}
              onChange={handleChange}
              placeholder="RPT-1001"
            />

            {/* REPORT TYPE */}
            <InputField
              label="Report Type"
              name="reportType"
              value={formData.reportType}
              onChange={handleChange}
              placeholder="Assessment Performance Report"
            />

            {/* GENERATED BY */}
            <InputField
              label="Generated By"
              name="generatedBy"
              value={formData.generatedBy}
              onChange={handleChange}
              placeholder="Sunil Kumar"
            />

            {/* ASSESSMENT ID */}
            <InputField
              label="Assessment ID"
              name="assessmentId"
              value={formData.assessmentId}
              onChange={handleChange}
              placeholder="ASM-1001"
            />

            {/* CAMPAIGN ID */}
            <InputField
              label="Campaign ID"
              name="campaignId"
              value={formData.campaignId}
              onChange={handleChange}
              placeholder="CMP-1001"
            />

            {/* AVERAGE SCORE */}
            <InputField
              label="Average Score"
              type="number"
              name="averageScore"
              value={formData.averageScore}
              onChange={handleChange}
              placeholder="78"
            />

            {/* HIGHEST SCORE */}
            <InputField
              label="Highest Score"
              type="number"
              name="highestScore"
              value={formData.highestScore}
              onChange={handleChange}
              placeholder="98"
            />

            {/* LOWEST SCORE */}
            <InputField
              label="Lowest Score"
              type="number"
              name="lowestScore"
              value={formData.lowestScore}
              onChange={handleChange}
              placeholder="42"
            />

            {/* COMPLETION RATE */}
            <InputField
              label="Completion Rate (%)"
              type="number"
              name="completionRate"
              value={formData.completionRate}
              onChange={handleChange}
              placeholder="84"
            />

            {/* SUSPICIOUS ACTIVITIES */}
            <InputField
              label="Suspicious Activities"
              type="number"
              name="suspiciousActivities"
              value={formData.suspiciousActivities}
              onChange={handleChange}
              placeholder="3"
            />

            {/* EXPORTED FORMAT */}
            <div>
              <label className="text-sm font-semibold text-gray-700">
                Exported Format
              </label>

              <select
                name="exportedFormat"
                value={formData.exportedFormat}
                onChange={handleChange}
                className="w-full mt-2 px-4 py-3 rounded-2xl border border-gray-300 outline-none focus:ring-2 focus:ring-blue-500"
              >
                <option>PDF</option>
                <option>Excel</option>
                <option>CSV</option>
              </select>
            </div>

            {/* GENERATED AT */}
            <InputField
              label="Generated At"
              type="date"
              name="generatedAt"
              value={formData.generatedAt}
              onChange={handleChange}
            />
          </div>

          {/* BUTTON */}
          <div className="mt-10 flex justify-end">
            <button
              type="submit"
              disabled={loading}
              className="
                px-8
                py-4
                rounded-2xl
                bg-linear-to-r
                from-blue-600
                to-indigo-600
                text-white
                font-semibold
                shadow-lg
                hover:scale-105
                transition-all
                duration-300
                disabled:opacity-50
                disabled:cursor-not-allowed
              "
            >
              {loading ? "Submitting..." : "Submit Report"}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}

/* INPUT FIELD */
function InputField({
  label,
  name,
  value,
  onChange,
  placeholder,
  type = "text",
}: InputFieldProps) {
  return (
    <div>
      <label className="text-sm font-semibold text-gray-700">
        {label}
      </label>

      <input
        type={type}
        name={name}
        value={value}
        onChange={onChange}
        placeholder={placeholder}
        className="
          w-full
          mt-2
          px-4
          py-3
          rounded-2xl
          border
          border-gray-300
          outline-none
          focus:ring-2
          focus:ring-blue-500
        "
      />
    </div>
  );
}