"use client";

import DataTable from "@/component/table";
import ActionButtons from "@/component/button";
import { useEffect, useState } from "react";  
import { API_BASE_URL, getRequest } from "@/util/APIGeneric";


const reportsAnalyticsData = [
  {
    reportId: "RPT-1001",

    reportType: "Assessment Performance Report",

    generatedBy: "Sunil Kumar",

    assessmentId: "ASM-1001",

    campaignId: "CMP-1001",

    averageScore: 78,
    highestScore: 98,
    lowestScore: 42,

    completionRate: 84,

    suspiciousActivities: 3,

    exportedFormat: "PDF",

    generatedAt: "2026-05-15",
  },

  {
    reportId: "RPT-1002",

    reportType: "Campaign Analytics Report",

    generatedBy: "HR Team",

    assessmentId: "ASM-1002",

    campaignId: "CMP-1002",

    averageScore: 69,
    highestScore: 92,
    lowestScore: 35,

    completionRate: 100,

    suspiciousActivities: 1,

    exportedFormat: "Excel",

    generatedAt: "2026-05-14",
  },
];

export default function ReportsAnalyticsPage() {

    const [data, setData] = useState([]);
  
    useEffect(() => {
  
      const fetchData = async () => {
        try {
  
          const response = await getRequest(
            `${API_BASE_URL}/report`
          );
  
          console.log("Fetched Data: report", response);
  
          setData(response);
  
        } catch (error) {
          console.log(error);
        }
      };
  
      fetchData();
  
    }, []);

  const columns = [

    // REPORT
    {
      header: "Report",

      render: (item) => (
        <div className="min-w-[320px]">

          <div className="flex items-start gap-4">

            <div className="
              w-14
              h-14
              rounded-2xl
              bg-gradient-to-r
              from-cyan-500
              to-blue-600
              flex
              items-center
              justify-center
              text-white
              font-bold
              text-lg
              shadow-lg
              shrink-0
            ">
              R
            </div>

            <div>

              <h2 className="font-bold text-gray-900 text-base">
                {item.reportType}
              </h2>

              <p className="text-xs text-gray-500 mt-1">
                {item.reportId}
              </p>

              <div className="flex items-center gap-2 mt-3">

                <span className="
                  bg-blue-100
                  text-blue-700
                  px-3
                  py-1
                  rounded-full
                  text-xs
                  font-semibold
                ">
                  {item.assessmentId}
                </span>

                <span className="
                  bg-purple-100
                  text-purple-700
                  px-3
                  py-1
                  rounded-full
                  text-xs
                  font-semibold
                ">
                  {item.campaignId}
                </span>

              </div>

            </div>

          </div>
        </div>
      ),
    },

    // GENERATED BY
    {
      header: "Generated By",

      render: (item) => (
        <div className="min-w-[180px]">

          <div className="
            bg-gray-100
            rounded-2xl
            px-4
            py-3
          ">
            <h3 className="font-semibold text-gray-800">
              {item.generatedBy}
            </h3>

            <p className="text-xs text-gray-500 mt-1">
              Report Creator
            </p>
          </div>

        </div>
      ),
    },

    // SCORE ANALYTICS
    {
      header: "Score Analytics",

      render: (item) => (
        <div className="min-w-[280px] space-y-3">

          <div className="flex items-center justify-between">

            <span className="text-sm text-gray-600">
              Average
            </span>

            <span className="
              bg-blue-100
              text-blue-700
              px-3
              py-1
              rounded-full
              text-xs
              font-bold
            ">
              {item.averageScore}%
            </span>
          </div>

          <div className="flex items-center justify-between">

            <span className="text-sm text-gray-600">
              Highest
            </span>

            <span className="
              bg-green-100
              text-green-700
              px-3
              py-1
              rounded-full
              text-xs
              font-bold
            ">
              {item.highestScore}%
            </span>
          </div>

          <div className="flex items-center justify-between">

            <span className="text-sm text-gray-600">
              Lowest
            </span>

            <span className="
              bg-red-100
              text-red-700
              px-3
              py-1
              rounded-full
              text-xs
              font-bold
            ">
              {item.lowestScore}%
            </span>
          </div>

        </div>
      ),
    },

    // COMPLETION RATE
    {
      header: "Completion Rate",

      render: (item) => (
        <div className="min-w-[220px]">

          <div className="flex items-center justify-between mb-2">

            <span className="font-bold text-emerald-700">
              {item.completionRate}%
            </span>

            <span className="text-xs text-gray-500">
              Completed
            </span>

          </div>

          <div className="
            w-full
            h-3
            rounded-full
            bg-gray-200
            overflow-hidden
          ">

            <div
              className="
                h-full
                rounded-full
                bg-gradient-to-r
                from-emerald-500
                to-green-600
              "
              style={{
                width: `${item.completionRate}%`,
              }}
            />

          </div>

        </div>
      ),
    },

    // SECURITY
    {
      header: "Security Insights",

      render: (item) => (
        <div className="min-w-[200px]">

          <div className="
            bg-red-100
            text-red-700
            px-4
            py-3
            rounded-2xl
            font-bold
            text-sm
            w-fit
          ">
            {item.suspiciousActivities} Activities
          </div>

          <p className="text-xs text-gray-500 mt-2">
            Suspicious Behavior Detected
          </p>

        </div>
      ),
    },

    // EXPORT FORMAT
    {
      header: "Export",

      render: (item) => (
        <div className="min-w-[180px]">

          <div
            className={`
              px-4
              py-3
              rounded-2xl
              text-sm
              font-bold
              w-fit

              ${item.exportedFormat === "PDF"
                ? "bg-red-100 text-red-700"
                : "bg-green-100 text-green-700"
              }
            `}
          >
            {item.exportedFormat}
          </div>

          <p className="text-xs text-gray-500 mt-2">
            Download Format
          </p>

        </div>
      ),
    },

    // GENERATED DATE
    {
      header: "Generated At",

      render: (item) => (
        <div className="min-w-[180px]">

          <div className="
            bg-gray-100
            rounded-2xl
            px-4
            py-3
          ">

            <h3 className="font-semibold text-gray-800">
              {item.generatedAt}
            </h3>

            <p className="text-xs text-gray-500 mt-1">
              Report Generated Date
            </p>

          </div>

        </div>
      ),
    },
  ];

  return (
    <div className="p-6 bg-gray-100 min-h-screen">

      <ActionButtons
        addUrl="/dashboard/reports/add"
        importUrl="/dashboard/reports/import"
        exportUrl="/dashboard/reports/export"

      // showExport={false}
      />

      <DataTable
        title="Reports & Analytics"
        columns={columns}
        data={reportsAnalyticsData}
      />

    </div>
  );
}