"use client";

import { useEffect, useState } from "react";
import {
  FiAlertTriangle,
  FiBarChart2,
  FiCalendar,
  FiDownload,
  FiFileText,
  FiPieChart,
  FiUser,
} from "react-icons/fi";

import { API_BASE_URL, getRequest } from "../../../util/APIGeneric";

import ActionButtons from "../../../component/button";
import DataTable from "../../../component/table";
import { ReportsAnalytics } from "@/type/report";
import { reportsAnalyticsData } from "@/dummyData/report";

export default function ReportsAnalyticsPage() {
  const [data, setData] = useState<ReportsAnalytics[]>(reportsAnalyticsData);
  const [search, setSearch] = useState<string>("");

  const filteredData = data.filter((item) =>
  (item.reportType + " " + item.reportId + " " + item.generatedBy)
      .toLowerCase()
      .includes(search.toLowerCase())
  );

  useEffect(() => {
    const fetchData = async () => {
      try {
        const response = await getRequest(`${API_BASE_URL}/report`);

        console.log("Fetched Data: Reports", response);

        if (response) {
          setData(response);
        }
      } catch (error) {
        console.log(error);
      }
    };

    fetchData();
  }, []);

  const columns = [
    // REPORT
    {
      header: "Report",

      render: (item: ReportsAnalytics) => (
        <div className="min-w-90 text-left">
          <div className="flex items-start gap-4">
            {/* ICON */}
            <div
              className="
                h-14
                w-14
                rounded-2xl
                bg-linear-to-br
                from-[#0F2B46]
                to-[#1E4D7B]
                flex
                items-center
                justify-center
                text-white
                shadow-sm
                shrink-0
              "
            >
              <FiFileText size={22} />
            </div>

            {/* CONTENT */}
            <div>
              <h2 className="font-semibold text-slate-800 text-[15px]">
                {item.reportType}
              </h2>

              <p className="text-xs text-slate-500 mt-1">{item.reportId}</p>

              <div className="flex items-center gap-2 mt-4 flex-wrap">
                <span
                  className="
                    px-3
                    py-1
                    rounded-full
                    bg-blue-50
                    border
                    border-blue-100
                    text-blue-700
                    text-xs
                    font-medium
                  "
                >
                  {item.assessmentId}
                </span>

                <span
                  className="
                    px-3
                    py-1
                    rounded-full
                    bg-violet-50
                    border
                    border-violet-100
                    text-violet-700
                    text-xs
                    font-medium
                  "
                >
                  {item.campaignId}
                </span>
              </div>
            </div>
          </div>
        </div>
      ),
    },

    // GENERATED BY
    {
      header: "Generated By",

      render: (item: ReportsAnalytics) => (
        <div className="min-w-[200px]">
          <div className="flex items-center gap-3">
            <div
              className="
                h-10
                w-10
                rounded-xl
                bg-slate-100
                text-slate-700
                flex
                items-center
                justify-center
              "
            >
              <FiUser />
            </div>

            <div>
              <h3 className="font-semibold text-slate-800">
                {item.generatedBy}
              </h3>

              <p className="text-xs text-slate-500 mt-1">Report Creator</p>
            </div>
          </div>
        </div>
      ),
    },

    // SCORE ANALYTICS
    {
      header: "Score Analytics",

      render: (item: ReportsAnalytics) => (
        <div className="min-w-[250px]">
          <div className="flex items-center gap-3 mb-5">
            <div
              className="
                h-10
                w-10
                rounded-xl
                bg-sky-50
                text-sky-600
                flex
                items-center
                justify-center
              "
            >
              <FiBarChart2 />
            </div>

            <div>
              <h3 className="font-semibold text-slate-800">
                Performance Metrics
              </h3>

              <p className="text-xs text-slate-500 mt-1">Candidate Scores</p>
            </div>
          </div>

          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <span className="text-sm text-slate-500">Average</span>

              <span
                className="
                  px-3
                  py-1
                  rounded-full
                  bg-blue-50
                  text-blue-700
                  text-xs
                  font-semibold
                "
              >
                {item.averageScore}%
              </span>
            </div>

            <div className="flex items-center justify-between">
              <span className="text-sm text-slate-500">Highest</span>

              <span
                className="
                  px-3
                  py-1
                  rounded-full
                  bg-emerald-50
                  text-emerald-700
                  text-xs
                  font-semibold
                "
              >
                {item.highestScore}%
              </span>
            </div>

            <div className="flex items-center justify-between">
              <span className="text-sm text-slate-500">Lowest</span>

              <span
                className="
                  px-3
                  py-1
                  rounded-full
                  bg-red-50
                  text-red-700
                  text-xs
                  font-semibold
                "
              >
                {item.lowestScore}%
              </span>
            </div>
          </div>
        </div>
      ),
    },

    // COMPLETION RATE
    {
      header: "Completion Rate",

      render: (item: ReportsAnalytics) => (
        <div className="min-w-65">
          <div className="flex items-center justify-between mb-3">
            <span className="text-sm text-slate-500">Completion</span>

            <span className="font-bold text-emerald-600">
              {item.completionRate}%
            </span>
          </div>

          <div className="w-full h-3 rounded-full bg-slate-200 overflow-hidden">
            <div
              className="
                h-full
                rounded-full
                bg-linear-to-r
                from-emerald-500
                to-green-600
              "
              style={{
                width: `${item.completionRate}%`,
              }}
            />
          </div>

          <div className="flex items-center gap-2 mt-3">
            <FiPieChart className="text-emerald-500 text-sm" />

            <p className="text-xs text-slate-500">Overall Completion Rate</p>
          </div>
        </div>
      ),
    },

    // SECURITY
    {
      header: "Security Insights",

      render: (item: ReportsAnalytics) => (
        <div className="min-w-[200px]">
          <div className="flex items-center gap-3">
            <div
              className="
                h-10
                w-10
                rounded-xl
                bg-red-50
                text-red-600
                flex
                items-center
                justify-center
              "
            >
              <FiAlertTriangle />
            </div>

            <div>
              <h3 className="font-semibold text-red-700">
                {item.suspiciousActivities}
              </h3>

              <p className="text-xs text-slate-500 mt-1">
                Suspicious Activities
              </p>
            </div>
          </div>
        </div>
      ),
    },

    // EXPORT
    {
      header: "Export",

      render: (item: ReportsAnalytics) => (
        <div className="min-w-[180px]">
          <div className="flex items-center gap-3">
            <div
              className={`
                h-10
                w-10
                rounded-xl
                flex
                items-center
                justify-center

                ${item.exportedFormat === "PDF"
                  ? "bg-red-50 text-red-600"
                  : "bg-emerald-50 text-emerald-600"
                }
              `}
            >
              <FiDownload />
            </div>

            <div>
              <div
                className={`
                  inline-flex
                  items-center
                  px-3
                  py-1
                  rounded-full
                  text-xs
                  font-semibold

                  ${item.exportedFormat === "PDF"
                    ? "bg-red-50 text-red-700"
                    : "bg-emerald-50 text-emerald-700"
                  }
                `}
              >
                {item.exportedFormat}
              </div>

              <p className="text-xs text-slate-500 mt-2">Download Format</p>
            </div>
          </div>
        </div>
      ),
    },

    // GENERATED DATE
    {
      header: "Generated At",

      render: (item: ReportsAnalytics) => (
        <div className="min-w-[200px]">
          <div className="flex items-start gap-3">
            <div
              className="
                h-10
                w-10
                rounded-xl
                bg-amber-50
                text-amber-600
                flex
                items-center
                justify-center
              "
            >
              <FiCalendar />
            </div>

            <div>
              <p className="text-sm font-semibold text-slate-700">
                {item.generatedAt}
              </p>

              <p className="text-xs text-slate-500 mt-1">
                Report Generated Date
              </p>
            </div>
          </div>
        </div>
      ),
    },
  ];

  return (
    <div
      className="
        min-h-screen
        bg-linear-to-br
        from-slate-50
        via-blue-50/30
        to-slate-100
        p-6
      "
    >
      <ActionButtons
        addUrl="/dashboard/reports/add"
        importUrl="/dashboard/reports/import"
        exportUrl="/dashboard/reports/export"

        showAdd={false}
        showImport={false}
        showExport={false}

        searchValue={search}
        onSearchChange={setSearch}
      />
      <div className="space-y-6">
        <DataTable title="Reports & Analytics" columns={columns} data={filteredData} />
      </div>
    </div>
  );
}
