import { Candidate } from "@/type/canditate";

export const candidateData: Candidate[] = [
  {
    candidateId: "CND-1001",
    firstName: "Sunil",
    lastName: "Kumar",
    email: "sunil@example.com",
    phone: "+91 9876543210",
    profileImage: "https://randomuser.me/api/portraits/men/1.jpg",
    resumeUrl: "https://example.com/resume.pdf",
    linkedinUrl: "https://linkedin.com/in/sunil",
    githubUrl: "https://github.com/sunil",
    skills: ["React", "Next.js", "Node.js"],
    experience: "2 Years",
    education: "BCA",
    currentStatus: "Completed",
    appliedPosition: "Frontend Developer",
    assignedAssessment: "React Skill Test",
    totalScore: 88,
    ranking: 5,
    createdAt: "2026-05-15",
  },
  {
    candidateId: "CND-1002",
    firstName: "Rahul",
    lastName: "Sharma",
    email: "rahul@example.com",
    phone: "+91 9876500001",
    profileImage: "https://randomuser.me/api/portraits/men/2.jpg",
    resumeUrl: "https://example.com/resume2.pdf",
    linkedinUrl: "https://linkedin.com/in/rahul",
    githubUrl: "https://github.com/rahul",
    skills: ["Vue.js", "Firebase", "Tailwind"],
    experience: "3 Years",
    education: "B.Tech",
    currentStatus: "Selected",
    appliedPosition: "Frontend Engineer",
    assignedAssessment: "Vue Assessment",
    totalScore: 92,
    ranking: 2,
    createdAt: "2026-05-12",
  },
  {
    candidateId: "CND-1001",
    firstName: "Sunil",
    lastName: "Kumar",
    email: "sunil@example.com",
    phone: "+91 9876543210",
    profileImage: "https://randomuser.me/api/portraits/men/1.jpg",
    resumeUrl: "https://example.com/resume.pdf",
    linkedinUrl: "https://linkedin.com/in/sunil",
    githubUrl: "https://github.com/sunil",
    skills: ["React", "Next.js", "Node.js"],
    experience: "2 Years",
    education: "BCA",
    currentStatus: "Completed",
    appliedPosition: "Frontend Developer",
    assignedAssessment: "React Skill Test",
    totalScore: 88,
    ranking: 5,
    createdAt: "2026-05-15",
  },
  {
    candidateId: "CND-1002",
    firstName: "Rahul",
    lastName: "Sharma",
    email: "rahul@example.com",
    phone: "+91 9876500001",
    profileImage: "https://randomuser.me/api/portraits/men/2.jpg",
    resumeUrl: "https://example.com/resume2.pdf",
    linkedinUrl: "https://linkedin.com/in/rahul",
    githubUrl: "https://github.com/rahul",
    skills: ["Vue.js", "Firebase", "Tailwind"],
    experience: "3 Years",
    education: "B.Tech",
    currentStatus: "Selected",
    appliedPosition: "Frontend Engineer",
    assignedAssessment: "Vue Assessment",
    totalScore: 92,
    ranking: 2,
    createdAt: "2026-05-12",
  },
  {
    candidateId: "CND-1001",
    firstName: "Sunil",
    lastName: "Kumar",
    email: "sunil@example.com",
    phone: "+91 9876543210",
    profileImage: "https://randomuser.me/api/portraits/men/1.jpg",
    resumeUrl: "https://example.com/resume.pdf",
    linkedinUrl: "https://linkedin.com/in/sunil",
    githubUrl: "https://github.com/sunil",
    skills: ["React", "Next.js", "Node.js"],
    experience: "2 Years",
    education: "BCA",
    currentStatus: "Completed",
    appliedPosition: "Frontend Developer",
    assignedAssessment: "React Skill Test",
    totalScore: 88,
    ranking: 5,
    createdAt: "2026-05-15",
  },
  {
    candidateId: "CND-1002",
    firstName: "Rahul",
    lastName: "Sharma",
    email: "rahul@example.com",
    phone: "+91 9876500001",
    profileImage: "https://randomuser.me/api/portraits/men/2.jpg",
    resumeUrl: "https://example.com/resume2.pdf",
    linkedinUrl: "https://linkedin.com/in/rahul",
    githubUrl: "https://github.com/rahul",
    skills: ["Vue.js", "Firebase", "Tailwind"],
    experience: "3 Years",
    education: "B.Tech",
    currentStatus: "Selected",
    appliedPosition: "Frontend Engineer",
    assignedAssessment: "Vue Assessment",
    totalScore: 92,
    ranking: 2,
    createdAt: "2026-05-12",
  },
  {
    candidateId: "CND-1001",
    firstName: "Sunil",
    lastName: "Kumar",
    email: "sunil@example.com",
    phone: "+91 9876543210",
    profileImage: "https://randomuser.me/api/portraits/men/1.jpg",
    resumeUrl: "https://example.com/resume.pdf",
    linkedinUrl: "https://linkedin.com/in/sunil",
    githubUrl: "https://github.com/sunil",
    skills: ["React", "Next.js", "Node.js"],
    experience: "2 Years",
    education: "BCA",
    currentStatus: "Completed",
    appliedPosition: "Frontend Developer",
    assignedAssessment: "React Skill Test",
    totalScore: 88,
    ranking: 5,
    createdAt: "2026-05-15",
  },
  {
    candidateId: "CND-1002",
    firstName: "Rahul",
    lastName: "Sharma",
    email: "rahul@example.com",
    phone: "+91 9876500001",
    profileImage: "https://randomuser.me/api/portraits/men/2.jpg",
    resumeUrl: "https://example.com/resume2.pdf",
    linkedinUrl: "https://linkedin.com/in/rahul",
    githubUrl: "https://github.com/rahul",
    skills: ["Vue.js", "Firebase", "Tailwind"],
    experience: "3 Years",
    education: "B.Tech",
    currentStatus: "Selected",
    appliedPosition: "Frontend Engineer",
    assignedAssessment: "Vue Assessment",
    totalScore: 92,
    ranking: 2,
    createdAt: "2026-05-12",
  },
  {
    candidateId: "CND-1001",
    firstName: "Sunil",
    lastName: "Kumar",
    email: "sunil@example.com",
    phone: "+91 9876543210",
    profileImage: "https://randomuser.me/api/portraits/men/1.jpg",
    resumeUrl: "https://example.com/resume.pdf",
    linkedinUrl: "https://linkedin.com/in/sunil",
    githubUrl: "https://github.com/sunil",
    skills: ["React", "Next.js", "Node.js"],
    experience: "2 Years",
    education: "BCA",
    currentStatus: "Completed",
    appliedPosition: "Frontend Developer",
    assignedAssessment: "React Skill Test",
    totalScore: 88,
    ranking: 5,
    createdAt: "2026-05-15",
  },
  {
    candidateId: "CND-1002",
    firstName: "Rahul",
    lastName: "Sharma",
    email: "rahul@example.com",
    phone: "+91 9876500001",
    profileImage: "https://randomuser.me/api/portraits/men/2.jpg",
    resumeUrl: "https://example.com/resume2.pdf",
    linkedinUrl: "https://linkedin.com/in/rahul",
    githubUrl: "https://github.com/rahul",
    skills: ["Vue.js", "Firebase", "Tailwind"],
    experience: "3 Years",
    education: "B.Tech",
    currentStatus: "Selected",
    appliedPosition: "Frontend Engineer",
    assignedAssessment: "Vue Assessment",
    totalScore: 92,
    ranking: 2,
    createdAt: "2026-05-12",
  },
  {
    candidateId: "CND-1001",
    firstName: "Sunil",
    lastName: "Kumar",
    email: "sunil@example.com",
    phone: "+91 9876543210",
    profileImage: "https://randomuser.me/api/portraits/men/1.jpg",
    resumeUrl: "https://example.com/resume.pdf",
    linkedinUrl: "https://linkedin.com/in/sunil",
    githubUrl: "https://github.com/sunil",
    skills: ["React", "Next.js", "Node.js"],
    experience: "2 Years",
    education: "BCA",
    currentStatus: "Completed",
    appliedPosition: "Frontend Developer",
    assignedAssessment: "React Skill Test",
    totalScore: 88,
    ranking: 5,
    createdAt: "2026-05-15",
  },
  {
    candidateId: "CND-1002",
    firstName: "Rahul",
    lastName: "Sharma",
    email: "rahul@example.com",
    phone: "+91 9876500001",
    profileImage: "https://randomuser.me/api/portraits/men/2.jpg",
    resumeUrl: "https://example.com/resume2.pdf",
    linkedinUrl: "https://linkedin.com/in/rahul",
    githubUrl: "https://github.com/rahul",
    skills: ["Vue.js", "Firebase", "Tailwind"],
    experience: "3 Years",
    education: "B.Tech",
    currentStatus: "Selected",
    appliedPosition: "Frontend Engineer",
    assignedAssessment: "Vue Assessment",
    totalScore: 92,
    ranking: 2,
    createdAt: "2026-05-12",
  },
  {
    candidateId: "CND-1001",
    firstName: "Sunil",
    lastName: "Kumar",
    email: "sunil@example.com",
    phone: "+91 9876543210",
    profileImage: "https://randomuser.me/api/portraits/men/1.jpg",
    resumeUrl: "https://example.com/resume.pdf",
    linkedinUrl: "https://linkedin.com/in/sunil",
    githubUrl: "https://github.com/sunil",
    skills: ["React", "Next.js", "Node.js"],
    experience: "2 Years",
    education: "BCA",
    currentStatus: "Completed",
    appliedPosition: "Frontend Developer",
    assignedAssessment: "React Skill Test",
    totalScore: 88,
    ranking: 5,
    createdAt: "2026-05-15",
  },
  {
    candidateId: "CND-1002",
    firstName: "Rahul",
    lastName: "Sharma",
    email: "rahul@example.com",
    phone: "+91 9876500001",
    profileImage: "https://randomuser.me/api/portraits/men/2.jpg",
    resumeUrl: "https://example.com/resume2.pdf",
    linkedinUrl: "https://linkedin.com/in/rahul",
    githubUrl: "https://github.com/rahul",
    skills: ["Vue.js", "Firebase", "Tailwind"],
    experience: "3 Years",
    education: "B.Tech",
    currentStatus: "Selected",
    appliedPosition: "Frontend Engineer",
    assignedAssessment: "Vue Assessment",
    totalScore: 92,
    ranking: 2,
    createdAt: "2026-05-12",
  },
  {
    candidateId: "CND-1001",
    firstName: "Sunil",
    lastName: "Kumar",
    email: "sunil@example.com",
    phone: "+91 9876543210",
    profileImage: "https://randomuser.me/api/portraits/men/1.jpg",
    resumeUrl: "https://example.com/resume.pdf",
    linkedinUrl: "https://linkedin.com/in/sunil",
    githubUrl: "https://github.com/sunil",
    skills: ["React", "Next.js", "Node.js"],
    experience: "2 Years",
    education: "BCA",
    currentStatus: "Completed",
    appliedPosition: "Frontend Developer",
    assignedAssessment: "React Skill Test",
    totalScore: 88,
    ranking: 5,
    createdAt: "2026-05-15",
  },
  {
    candidateId: "CND-1002",
    firstName: "Rahul",
    lastName: "Sharma",
    email: "rahul@example.com",
    phone: "+91 9876500001",
    profileImage: "https://randomuser.me/api/portraits/men/2.jpg",
    resumeUrl: "https://example.com/resume2.pdf",
    linkedinUrl: "https://linkedin.com/in/rahul",
    githubUrl: "https://github.com/rahul",
    skills: ["Vue.js", "Firebase", "Tailwind"],
    experience: "3 Years",
    education: "B.Tech",
    currentStatus: "Selected",
    appliedPosition: "Frontend Engineer",
    assignedAssessment: "Vue Assessment",
    totalScore: 92,
    ranking: 2,
    createdAt: "2026-05-12",
  },
  {
    candidateId: "CND-1001",
    firstName: "Sunil",
    lastName: "Kumar",
    email: "sunil@example.com",
    phone: "+91 9876543210",
    profileImage: "https://randomuser.me/api/portraits/men/1.jpg",
    resumeUrl: "https://example.com/resume.pdf",
    linkedinUrl: "https://linkedin.com/in/sunil",
    githubUrl: "https://github.com/sunil",
    skills: ["React", "Next.js", "Node.js"],
    experience: "2 Years",
    education: "BCA",
    currentStatus: "Completed",
    appliedPosition: "Frontend Developer",
    assignedAssessment: "React Skill Test",
    totalScore: 88,
    ranking: 5,
    createdAt: "2026-05-15",
  },
  {
    candidateId: "CND-1002",
    firstName: "Rahul",
    lastName: "Sharma",
    email: "rahul@example.com",
    phone: "+91 9876500001",
    profileImage: "https://randomuser.me/api/portraits/men/2.jpg",
    resumeUrl: "https://example.com/resume2.pdf",
    linkedinUrl: "https://linkedin.com/in/rahul",
    githubUrl: "https://github.com/rahul",
    skills: ["Vue.js", "Firebase", "Tailwind"],
    experience: "3 Years",
    education: "B.Tech",
    currentStatus: "Selected",
    appliedPosition: "Frontend Engineer",
    assignedAssessment: "Vue Assessment",
    totalScore: 92,
    ranking: 2,
    createdAt: "2026-05-12",
  },
  {
    candidateId: "CND-1001",
    firstName: "Sunil",
    lastName: "Kumar",
    email: "sunil@example.com",
    phone: "+91 9876543210",
    profileImage: "https://randomuser.me/api/portraits/men/1.jpg",
    resumeUrl: "https://example.com/resume.pdf",
    linkedinUrl: "https://linkedin.com/in/sunil",
    githubUrl: "https://github.com/sunil",
    skills: ["React", "Next.js", "Node.js"],
    experience: "2 Years",
    education: "BCA",
    currentStatus: "Completed",
    appliedPosition: "Frontend Developer",
    assignedAssessment: "React Skill Test",
    totalScore: 88,
    ranking: 5,
    createdAt: "2026-05-15",
  },
  {
    candidateId: "CND-1002",
    firstName: "Rahul",
    lastName: "Sharma",
    email: "rahul@example.com",
    phone: "+91 9876500001",
    profileImage: "https://randomuser.me/api/portraits/men/2.jpg",
    resumeUrl: "https://example.com/resume2.pdf",
    linkedinUrl: "https://linkedin.com/in/rahul",
    githubUrl: "https://github.com/rahul",
    skills: ["Vue.js", "Firebase", "Tailwind"],
    experience: "3 Years",
    education: "B.Tech",
    currentStatus: "Selected",
    appliedPosition: "Frontend Engineer",
    assignedAssessment: "Vue Assessment",
    totalScore: 92,
    ranking: 2,
    createdAt: "2026-05-12",
  },
  {
    candidateId: "CND-1001",
    firstName: "Sunil",
    lastName: "Kumar",
    email: "sunil@example.com",
    phone: "+91 9876543210",
    profileImage: "https://randomuser.me/api/portraits/men/1.jpg",
    resumeUrl: "https://example.com/resume.pdf",
    linkedinUrl: "https://linkedin.com/in/sunil",
    githubUrl: "https://github.com/sunil",
    skills: ["React", "Next.js", "Node.js"],
    experience: "2 Years",
    education: "BCA",
    currentStatus: "Completed",
    appliedPosition: "Frontend Developer",
    assignedAssessment: "React Skill Test",
    totalScore: 88,
    ranking: 5,
    createdAt: "2026-05-15",
  },
  {
    candidateId: "CND-1002",
    firstName: "Rahul",
    lastName: "Sharma",
    email: "rahul@example.com",
    phone: "+91 9876500001",
    profileImage: "https://randomuser.me/api/portraits/men/2.jpg",
    resumeUrl: "https://example.com/resume2.pdf",
    linkedinUrl: "https://linkedin.com/in/rahul",
    githubUrl: "https://github.com/rahul",
    skills: ["Vue.js", "Firebase", "Tailwind"],
    experience: "3 Years",
    education: "B.Tech",
    currentStatus: "Selected",
    appliedPosition: "Frontend Engineer",
    assignedAssessment: "Vue Assessment",
    totalScore: 92,
    ranking: 2,
    createdAt: "2026-05-12",
  },
  {
    candidateId: "CND-1001",
    firstName: "Sunil",
    lastName: "Kumar",
    email: "sunil@example.com",
    phone: "+91 9876543210",
    profileImage: "https://randomuser.me/api/portraits/men/1.jpg",
    resumeUrl: "https://example.com/resume.pdf",
    linkedinUrl: "https://linkedin.com/in/sunil",
    githubUrl: "https://github.com/sunil",
    skills: ["React", "Next.js", "Node.js"],
    experience: "2 Years",
    education: "BCA",
    currentStatus: "Completed",
    appliedPosition: "Frontend Developer",
    assignedAssessment: "React Skill Test",
    totalScore: 88,
    ranking: 5,
    createdAt: "2026-05-15",
  },
  {
    candidateId: "CND-1002",
    firstName: "Rahul",
    lastName: "Sharma",
    email: "rahul@example.com",
    phone: "+91 9876500001",
    profileImage: "https://randomuser.me/api/portraits/men/2.jpg",
    resumeUrl: "https://example.com/resume2.pdf",
    linkedinUrl: "https://linkedin.com/in/rahul",
    githubUrl: "https://github.com/rahul",
    skills: ["Vue.js", "Firebase", "Tailwind"],
    experience: "3 Years",
    education: "B.Tech",
    currentStatus: "Selected",
    appliedPosition: "Frontend Engineer",
    assignedAssessment: "Vue Assessment",
    totalScore: 92,
    ranking: 2,
    createdAt: "2026-05-12",
  },
  {
    candidateId: "CND-1001",
    firstName: "Sunil",
    lastName: "Kumar",
    email: "sunil@example.com",
    phone: "+91 9876543210",
    profileImage: "https://randomuser.me/api/portraits/men/1.jpg",
    resumeUrl: "https://example.com/resume.pdf",
    linkedinUrl: "https://linkedin.com/in/sunil",
    githubUrl: "https://github.com/sunil",
    skills: ["React", "Next.js", "Node.js"],
    experience: "2 Years",
    education: "BCA",
    currentStatus: "Completed",
    appliedPosition: "Frontend Developer",
    assignedAssessment: "React Skill Test",
    totalScore: 88,
    ranking: 5,
    createdAt: "2026-05-15",
  },
  {
    candidateId: "CND-1002",
    firstName: "Rahul",
    lastName: "Sharma",
    email: "rahul@example.com",
    phone: "+91 9876500001",
    profileImage: "https://randomuser.me/api/portraits/men/2.jpg",
    resumeUrl: "https://example.com/resume2.pdf",
    linkedinUrl: "https://linkedin.com/in/rahul",
    githubUrl: "https://github.com/rahul",
    skills: ["Vue.js", "Firebase", "Tailwind"],
    experience: "3 Years",
    education: "B.Tech",
    currentStatus: "Selected",
    appliedPosition: "Frontend Engineer",
    assignedAssessment: "Vue Assessment",
    totalScore: 92,
    ranking: 2,
    createdAt: "2026-05-12",
  },
  {
    candidateId: "CND-1001",
    firstName: "Sunil",
    lastName: "Kumar",
    email: "sunil@example.com",
    phone: "+91 9876543210",
    profileImage: "https://randomuser.me/api/portraits/men/1.jpg",
    resumeUrl: "https://example.com/resume.pdf",
    linkedinUrl: "https://linkedin.com/in/sunil",
    githubUrl: "https://github.com/sunil",
    skills: ["React", "Next.js", "Node.js"],
    experience: "2 Years",
    education: "BCA",
    currentStatus: "Completed",
    appliedPosition: "Frontend Developer",
    assignedAssessment: "React Skill Test",
    totalScore: 88,
    ranking: 5,
    createdAt: "2026-05-15",
  },
  {
    candidateId: "CND-1002",
    firstName: "Rahul",
    lastName: "Sharma",
    email: "rahul@example.com",
    phone: "+91 9876500001",
    profileImage: "https://randomuser.me/api/portraits/men/2.jpg",
    resumeUrl: "https://example.com/resume2.pdf",
    linkedinUrl: "https://linkedin.com/in/rahul",
    githubUrl: "https://github.com/rahul",
    skills: ["Vue.js", "Firebase", "Tailwind"],
    experience: "3 Years",
    education: "B.Tech",
    currentStatus: "Selected",
    appliedPosition: "Frontend Engineer",
    assignedAssessment: "Vue Assessment",
    totalScore: 92,
    ranking: 2,
    createdAt: "2026-05-12",
  },
  {
    candidateId: "CND-1001",
    firstName: "Sunil",
    lastName: "Kumar",
    email: "sunil@example.com",
    phone: "+91 9876543210",
    profileImage: "https://randomuser.me/api/portraits/men/1.jpg",
    resumeUrl: "https://example.com/resume.pdf",
    linkedinUrl: "https://linkedin.com/in/sunil",
    githubUrl: "https://github.com/sunil",
    skills: ["React", "Next.js", "Node.js"],
    experience: "2 Years",
    education: "BCA",
    currentStatus: "Completed",
    appliedPosition: "Frontend Developer",
    assignedAssessment: "React Skill Test",
    totalScore: 88,
    ranking: 5,
    createdAt: "2026-05-15",
  },
  {
    candidateId: "CND-1002",
    firstName: "Rahul",
    lastName: "Sharma",
    email: "rahul@example.com",
    phone: "+91 9876500001",
    profileImage: "https://randomuser.me/api/portraits/men/2.jpg",
    resumeUrl: "https://example.com/resume2.pdf",
    linkedinUrl: "https://linkedin.com/in/rahul",
    githubUrl: "https://github.com/rahul",
    skills: ["Vue.js", "Firebase", "Tailwind"],
    experience: "3 Years",
    education: "B.Tech",
    currentStatus: "Selected",
    appliedPosition: "Frontend Engineer",
    assignedAssessment: "Vue Assessment",
    totalScore: 92,
    ranking: 2,
    createdAt: "2026-05-12",
  },
  {
    candidateId: "CND-1001",
    firstName: "Sunil",
    lastName: "Kumar",
    email: "sunil@example.com",
    phone: "+91 9876543210",
    profileImage: "https://randomuser.me/api/portraits/men/1.jpg",
    resumeUrl: "https://example.com/resume.pdf",
    linkedinUrl: "https://linkedin.com/in/sunil",
    githubUrl: "https://github.com/sunil",
    skills: ["React", "Next.js", "Node.js"],
    experience: "2 Years",
    education: "BCA",
    currentStatus: "Completed",
    appliedPosition: "Frontend Developer",
    assignedAssessment: "React Skill Test",
    totalScore: 88,
    ranking: 5,
    createdAt: "2026-05-15",
  },
  {
    candidateId: "CND-1002",
    firstName: "Rahul",
    lastName: "Sharma",
    email: "rahul@example.com",
    phone: "+91 9876500001",
    profileImage: "https://randomuser.me/api/portraits/men/2.jpg",
    resumeUrl: "https://example.com/resume2.pdf",
    linkedinUrl: "https://linkedin.com/in/rahul",
    githubUrl: "https://github.com/rahul",
    skills: ["Vue.js", "Firebase", "Tailwind"],
    experience: "3 Years",
    education: "B.Tech",
    currentStatus: "Selected",
    appliedPosition: "Frontend Engineer",
    assignedAssessment: "Vue Assessment",
    totalScore: 92,
    ranking: 2,
    createdAt: "2026-05-12",
  },
  {
    candidateId: "CND-1001",
    firstName: "Sunil",
    lastName: "Kumar",
    email: "sunil@example.com",
    phone: "+91 9876543210",
    profileImage: "https://randomuser.me/api/portraits/men/1.jpg",
    resumeUrl: "https://example.com/resume.pdf",
    linkedinUrl: "https://linkedin.com/in/sunil",
    githubUrl: "https://github.com/sunil",
    skills: ["React", "Next.js", "Node.js"],
    experience: "2 Years",
    education: "BCA",
    currentStatus: "Completed",
    appliedPosition: "Frontend Developer",
    assignedAssessment: "React Skill Test",
    totalScore: 88,
    ranking: 5,
    createdAt: "2026-05-15",
  },
  {
    candidateId: "CND-1002",
    firstName: "Rahul",
    lastName: "Sharma",
    email: "rahul@example.com",
    phone: "+91 9876500001",
    profileImage: "https://randomuser.me/api/portraits/men/2.jpg",
    resumeUrl: "https://example.com/resume2.pdf",
    linkedinUrl: "https://linkedin.com/in/rahul",
    githubUrl: "https://github.com/rahul",
    skills: ["Vue.js", "Firebase", "Tailwind"],
    experience: "3 Years",
    education: "B.Tech",
    currentStatus: "Selected",
    appliedPosition: "Frontend Engineer",
    assignedAssessment: "Vue Assessment",
    totalScore: 92,
    ranking: 2,
    createdAt: "2026-05-12",
  },
  {
    candidateId: "CND-1001",
    firstName: "Sunil",
    lastName: "Kumar",
    email: "sunil@example.com",
    phone: "+91 9876543210",
    profileImage: "https://randomuser.me/api/portraits/men/1.jpg",
    resumeUrl: "https://example.com/resume.pdf",
    linkedinUrl: "https://linkedin.com/in/sunil",
    githubUrl: "https://github.com/sunil",
    skills: ["React", "Next.js", "Node.js"],
    experience: "2 Years",
    education: "BCA",
    currentStatus: "Completed",
    appliedPosition: "Frontend Developer",
    assignedAssessment: "React Skill Test",
    totalScore: 88,
    ranking: 5,
    createdAt: "2026-05-15",
  },
  {
    candidateId: "CND-1002",
    firstName: "Rahul",
    lastName: "Sharma",
    email: "rahul@example.com",
    phone: "+91 9876500001",
    profileImage: "https://randomuser.me/api/portraits/men/2.jpg",
    resumeUrl: "https://example.com/resume2.pdf",
    linkedinUrl: "https://linkedin.com/in/rahul",
    githubUrl: "https://github.com/rahul",
    skills: ["Vue.js", "Firebase", "Tailwind"],
    experience: "3 Years",
    education: "B.Tech",
    currentStatus: "Selected",
    appliedPosition: "Frontend Engineer",
    assignedAssessment: "Vue Assessment",
    totalScore: 92,
    ranking: 2,
    createdAt: "2026-05-12",
  },
  {
    candidateId: "CND-1001",
    firstName: "Sunil",
    lastName: "Kumar",
    email: "sunil@example.com",
    phone: "+91 9876543210",
    profileImage: "https://randomuser.me/api/portraits/men/1.jpg",
    resumeUrl: "https://example.com/resume.pdf",
    linkedinUrl: "https://linkedin.com/in/sunil",
    githubUrl: "https://github.com/sunil",
    skills: ["React", "Next.js", "Node.js"],
    experience: "2 Years",
    education: "BCA",
    currentStatus: "Completed",
    appliedPosition: "Frontend Developer",
    assignedAssessment: "React Skill Test",
    totalScore: 88,
    ranking: 5,
    createdAt: "2026-05-15",
  },
  {
    candidateId: "CND-1002",
    firstName: "Rahul",
    lastName: "Sharma",
    email: "rahul@example.com",
    phone: "+91 9876500001",
    profileImage: "https://randomuser.me/api/portraits/men/2.jpg",
    resumeUrl: "https://example.com/resume2.pdf",
    linkedinUrl: "https://linkedin.com/in/rahul",
    githubUrl: "https://github.com/rahul",
    skills: ["Vue.js", "Firebase", "Tailwind"],
    experience: "3 Years",
    education: "B.Tech",
    currentStatus: "Selected",
    appliedPosition: "Frontend Engineer",
    assignedAssessment: "Vue Assessment",
    totalScore: 92,
    ranking: 2,
    createdAt: "2026-05-12",
  },
];
